"""Offline integration acceptance tests for the parallel self-test runner.

All SDK behavior is replaced by a deterministic fake; these tests must never
make model/provider calls.
"""
from __future__ import annotations

import asyncio
import json
from pathlib import Path
from types import SimpleNamespace

import pytest

from nova.benchmark_parallel_cases import load_corpus
from nova.benchmark_parallel_report import ARMS, summarize_report
import scripts.run_parallel_selftest as runner


def _args(tmp_path: Path, *, dependency_audit_approved: bool = False):
    return SimpleNamespace(
        stage="development", corpus=str(runner.DEFAULT_CORPUS),
        output=str(tmp_path / "run"), model="test-fake-only",
        reasoning_effort="medium", enable_model_calls=True,
        dependency_audit_approved=dependency_audit_approved,
        offline_gold_fixture=False,
    )


def _fake_response(case):
    return json.dumps({
        "answers": {q["id"]: q["expected"] for q in case["questions"]},
        "citations": case["required_citations"],
        "explanation": "synthetic-only; generated by offline fake runtime.",
    })


def _patch_output(monkeypatch, tmp_path):
    outdir = tmp_path / "run"

    def create_run_directory(_requested=None):
        outdir.mkdir(parents=True, exist_ok=False)
        return outdir

    monkeypatch.setattr(runner, "create_run_directory", create_run_directory)
    return outdir


def test_development_runner_reserves_24_turns_and_runs_arms_sequentially(monkeypatch, tmp_path):
    outdir = _patch_output(monkeypatch, tmp_path)
    corpus = load_corpus()
    by_packet = {case["packet"]: case for case in corpus["development"]}
    callbacks = []
    arm_order = []
    active, max_active = 0, 0

    async def fake_run_arm(packet, arm, model, reasoning_effort, before_dispatch,
                           turn_timeout=45, arm_timeout=150):
        nonlocal active, max_active
        case = by_packet[packet]
        active += 1
        max_active = max(max_active, active)
        arm_order.append((case["id"], arm))
        roles = {"single_self_review": ("draft", "critique", "final"),
                 "parallel_review": ("planner", "skeptic", "pi")}[arm]
        try:
            for role in roles:
                await before_dispatch(role)
                callbacks.append((case["id"], arm, role))
                await asyncio.sleep(0)
            return {"status": "success", "cleanup_ok": True,
                    "final_raw": _fake_response(case),
                    "turns": [{"status": "success",
                               "thread_id": "single-stable-thread" if arm == "single_self_review"
                               else f"parallel-{role}-thread"} for role in roles],
                    "wall_seconds": 0.001, "error": None}
        finally:
            active -= 1

    import nova.benchmark_parallel_runtime as runtime
    monkeypatch.setattr(runtime, "run_arm", fake_run_arm)
    result = asyncio.run(runner._run(_args(tmp_path)))

    report = json.loads((outdir / "report.json").read_text())
    assert result == 0
    assert report["sdk_turns_reserved"] == 24
    assert len(callbacks) == 24
    assert sum(bool(report["groups"][0]["arms"][arm]["delivery_valid"]) for arm in ARMS) == 2
    assert all(sum(group["arms"][arm]["delivery_valid"] for group in report["groups"])
               == 4 for arm in ARMS)
    assert max_active == 1, "the two arms must be sequential; the parallel arm owns its own two slots"
    for group in report["groups"]:
        observed = [arm for cid, arm in arm_order if cid == group["case_id"]]
        assert observed == group["scheduled_arm_order"]
        single_ids = {turn["thread_id"] for turn in group["arms"]["single_self_review"]["turns"]}
        parallel_ids = {turn["thread_id"] for turn in group["arms"]["parallel_review"]["turns"]}
        assert single_ids == {"single-stable-thread"}
        assert len(parallel_ids) == 3
    assert report["runner_status"] == "completed"


@pytest.mark.parametrize("failure_kind", ["fatal_audit", "cleanup_false"])
def test_audit_or_cleanup_failure_aborts_before_any_later_sdk_dispatch(
    monkeypatch, tmp_path, failure_kind
):
    _patch_output(monkeypatch, tmp_path)
    corpus = load_corpus()
    by_packet = {case["packet"]: case for case in corpus["development"]}
    callbacks = []

    async def fake_run_arm(packet, arm, model, reasoning_effort, before_dispatch,
                           turn_timeout=45, arm_timeout=150):
        case = by_packet[packet]
        first_role = {"single_self_review": "draft", "parallel_review": "planner"}[arm]
        await before_dispatch(first_role)
        callbacks.append((case["id"], arm, first_role))
        if failure_kind == "fatal_audit":
            return {"status": "fatal_audit_error", "fatal_audit": True,
                    "cleanup_ok": True, "final_raw": None, "turns": [],
                    "error": "injected audit failure"}
        roles = {"single_self_review": ("critique", "final"),
                 "parallel_review": ("skeptic", "pi")}[arm]
        for role in roles:
            await before_dispatch(role)
            callbacks.append((case["id"], arm, role))
        return {"status": "success", "cleanup_ok": False,
                "final_raw": _fake_response(case), "turns": [{"status": "success"}] * 3,
                "wall_seconds": 0.001, "error": "cleanup unconfirmed"}

    import nova.benchmark_parallel_runtime as runtime
    monkeypatch.setattr(runtime, "run_arm", fake_run_arm)
    result = asyncio.run(runner._run(_args(tmp_path)))
    assert result != 0
    assert len(callbacks) == (1 if failure_kind == "fatal_audit" else 3)


def _summary_group(case_id, repetition, penalty=2.0, utility=1.0):
    return {
        "case_id": case_id, "repetition": repetition,
        "arms": {arm: {"status": "completed", "deadline_penalty_seconds": penalty,
                       "structured_delivery_utility": utility,
                       "delivery_valid": True, "observed_delivery_seconds": 1.0}
                 for arm in ARMS},
    }


@pytest.mark.parametrize("groups", [
    [_summary_group("case-a", 1), _summary_group("case-a", 1)],  # duplicated repetition
    [_summary_group("case-a", 1)],  # missing repetition
])
def test_duplicate_or_missing_repetition_suppresses_pair_and_primary_summary(groups):
    case = {"id": "case-a", "family": "quantity", "pair_id": "pair-a", "variant": 1}
    report = {"cases": [case], "groups": groups, "repetitions": 2}
    summary = summarize_report(report, dependency_audit_approved=True)
    assert report["case_summaries"][0]["complete"] is False
    assert report["case_summaries"][0]["pair_complete"] is False
    assert summary["paired_cases_complete"] == 0
    assert summary["structured_time_gain_median"] is None
    assert summary["structured_utility_delta_mean"] is None
    assert summary["descriptive_interval"] is None
